# Generated by Django 5.0.13 on 2025-12-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLavanderia',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('direccion_recogida', models.CharField(blank=True, max_length=255)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('notas_cliente', models.TextField(blank=True, null=True)),
                ('preferencias_lavado', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoLavanderia',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turno', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaLavanderia',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_maquina', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('capacidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estado_operativo', models.CharField(max_length=50)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('num_serie', models.CharField(blank=True, max_length=50)),
                ('es_lavadora', models.BooleanField(default=False)),
                ('es_secadora', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloRopa',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_prenda', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('tamano', models.CharField(max_length=20)),
                ('instrucciones_especiales', models.TextField(blank=True, null=True)),
                ('costo_lavado_estandar', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estado_articulo', models.CharField(max_length=50)),
                ('es_delicado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='app_lavanderia27.clientelavanderia')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoLavanderia',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('estado_pedido', models.CharField(max_length=50)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('comentarios_cliente', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_lavanderia27.clientelavanderia')),
                ('empleado_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recepcion', to='app_lavanderia27.empleadolavanderia')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoLavanderia',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('costo_servicio_individual', models.DecimalField(decimal_places=2, max_digits=7)),
                ('subtotal_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manchas_detectadas', models.TextField(blank=True, null=True)),
                ('instrucciones_item', models.TextField(blank=True, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='app_lavanderia27.articuloropa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_lavanderia27.pedidolavanderia')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteOperacional',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('num_pedidos_procesados', models.IntegerField(default=0)),
                ('kg_ropa_procesada', models.IntegerField(default=0)),
                ('tiempo_inactividad_maquinas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones_turno', models.TextField(blank=True, null=True)),
                ('consumo_agua_litros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='app_lavanderia27.empleadolavanderia')),
            ],
        ),
    ]
