# Generated by Django 5.0.13 on 2025-12-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lavanderia27', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteoperacional',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='app_lavanderia27.empleadolavanderia'),
        ),
    ]
